name: Dotnet abstractions

on:
  push:
    branches: [ main ]
    paths: ['abstractions/dotnet/**', '.github/workflows/**']
  pull_request:
    paths: ['abstractions/dotnet/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./abstractions/dotnet
      solutionName: Microsoft.Kiota.Abstractions.sln
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
        working-directory: ${{ env.relativePath }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Release
        working-directory: ${{ env.relativePath }}
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Publish
        run: dotnet publish ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Pack
        run: dotnet pack ${{ env.solutionName }} --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/src/bin/Release/*.nupkg
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.x
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: dotnet nuget push "*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/microsoft/index.json -k ${{ secrets.PUBLISH_GH_TOKEN }}
