name: Typescript Authentication Azure

on:
  push:
    branches: [ main ]
    paths: ['authentication/typescript/azure/**', '.github/workflows/**']
  pull_request:
    paths: ['authentication/typescript/azure/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./authentication/typescript/azure
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          always-auth: true
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@microsoft'
      - run: npm ci
        working-directory: ${{ env.relativePath }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build
        working-directory: ${{ env.relativePath }}
      # - run: npm run test
      #   working-directory: ${{ env.relativePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/dist/
            ${{ env.relativePath }}/.npmignore
            ${{ env.relativePath }}/README.md
            ${{ env.relativePath }}/package.json
            ${{ env.relativePath }}/package-lock.json
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_GH_TOKEN }}" > .npmrc
      - run: npm publish
      - run: rm .npmrc
        if: always()
